name: first GH-Actions-test
on:
  push:

jobs: 
  test-first-gha-job:
   runs-on: self-hosted
  
   steps: 
     - name: message
       run: echo "welcome to Github-actions form rk"



















